baseURL = "https://michaelmalick.com/"
locale = "en-us"
enableRobotsTXT = true
title = "Michael Malick"
disableKinds = ["taxonomy", "term"]

[params]
  description = "Personal website of Michael Malick, quantitative ecologist at NOAA Fisheries"
  author = "Michael Malick"
  image = "/images/michael_malick.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
